[build]
  publish = "."   # đổi nếu file html nằm trong /public, /dist,...
  # command = "npm run build"  # nếu cần

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Tuỳ chọn: map /api/* → /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
